<?php
// Auto-generated by crontab_sync.php
if (!isset($argv) || !is_array($argv)) {
    $argv = [__FILE__];
}
$argv[] = '--pemilik=MEDIAQ';
require '/var/www/quenbytekniksejahtera/crm/crm/billing/notifbot/notifphp/cron_dismantle_ticket.php';
